# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_dispatch:
#  push:
#    branches: [ "master" ]
#  pull_request:
#    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - id: "auth"
      uses: "google-github-actions/auth@v1"
      with:
        credentials_json: "${{secrets.GCP_SA_KEY}}"
    - name: Set up gcloud Cloud SDK environment
      uses: google-github-actions/setup-gcloud@v2.1.0
    - name: "Use gcloud CLI"
      run: "gcloud info"
    - name: "Docker auth" # us-central1-docker.pkg.dev/cool-subset-426206-j9/docker-repo
      run: gcloud auth configure-docker us-central1-docker.pkg.dev
    - name: "Docker login"
      run: docker login
    - name: Build with Maven and Push
      run: mvn clean compile jib:build
    - name: GKE gcloud auth plugin install
      run: gcloud components install gke-gcloud-auth-plugin
    - name: Get kubectl credentials
      run: gcloud container clusters get-credentials my-first-cluster-1 --zone us-central1-c
    # - name: Kubectl create secret
    #   run: kubectl create secret docker-registry gcr-access-token --docker-server=https://gcr.io --docker-username=gke_cool-subset-426206-j9_us-central1-c_my-first-cluster-1 --docker-password="$(gcloud auth print-access-token)" --docker-email=any@valid.email
    # - name: Patch secret with account
    #   run: kubectl patch serviceaccount gke_cool-subset-426206-j9_us-central1-c_my-first-cluster-1 -p '{"imagePullSecrets": [{"name": "gcr-json-key"}]}'
    - name: Config details
      run: kubectl config view --raw
    - name: Kubectl test
      run: kubectl get serviceaccounts -n=default
    - name: Deploy helm chart
      run: helm upgrade -i educative .devops/educative-helm --version 0.1.1
    #- name: Rename tag
    #  run: docker tag educative us-central1-docker.pkg.dev/cool-subset-426206-j9/docker-repo
    #- name: Push to registry
    #  run: docker push us-central1-docker.pkg.dev/cool-subset-426206-j9/docker-repo

    
    
    

    # Optional: Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #  uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6
